[package]
name        = "bevy_mod_reqwest"
description = "Bevy http client using reqwest, with a focus on simple usage within the bevy runtime"
version     = "0.22.1"
edition     = "2021"
readme      = "README.md"
authors     = ["Kristoffer Ödmark <kristoffer.odmark90@gmail.com>"]
repository  = "https://github.com/TotalKrill/bevy_mod_reqwest.git"
license     = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default     = ["rustls", "json", "log"]
default-tls = ["reqwest/default-tls"]
json        = ["reqwest/json", "serde_json"]
rustls      = ["reqwest/rustls"]
msgpack     = ["rmp-serde"]
log         = ["bevy/bevy_log"]
query       = ["reqwest/query"]

[dependencies]
bevy           = { git = "https://github.com/bevyengine/bevy.git", default-features = false }
reqwest        = { version = "0.13", default-features = false }
rmp-serde      = { version = "1.3.1", optional = true}
serde          = { version = "1.0.228", features = ["derive"] }
serde_json     = { version = "1", optional = true }

anyhow         = "1.0.102"
bytes          = "1.12.0"
futures-lite   = "2.6.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
crossbeam-channel = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-compat = "0.2"
